# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 507dfb288c72ea0f337cdde417fabcd7cd370bae32ac546668e5af10e670b8820dd83814530da1b5632604ea8a27205aa82e92a9b8948f98d913c662912b7d88

test:
  secret_key_base: dcd69e70fcf0e27f66e95b9077dbe747ad31727831112b091faf04500829fb431d071c2b9a75ae2a73888809964003b9fec776bfa45a762fb1f89400b3d70565

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
